name: build
defaults:
  run:
    shell: bash
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  push:
    branches:
      - master
  pull_request: {}
  release:
    types: [created]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            coverage/
            dist/
            .npmignore
            package.json
            package-lock.json
            LICENSE
            README.md

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - if: success()
        uses: actions/download-artifact@v2
        id: download
        with:
          name: build-artifacts
      - run: go test -v -covermode=count -coverprofile=coverage.out
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info

  publish:
    needs: build
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - if: success()
        uses: actions/download-artifact@v2
        id: download
        with:
          name: build-artifacts
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
